### PR TITLE
install: add asdf

### PR DESCRIPTION
**Pull request by noraj**
Add [asdf-vm](https://asdf-vm.com/) / [asdf-ruby](https://github.com/asdf-vm/asdf-ruby) install step.

### CODE REVIEW

**Comment by lopopolo** [comment]
@noraj can you attach a screenshot of what this looks like?

**Comment by noraj** [comment]
image

rbenv use ruby-build, asdf use ruby-build too so it's all the same.

**Comment by lopopolo** [comment]
sorry for not being specific. Since this PR is changing a webpage, can you provide a screenshot of the webpage.

**Comment by noraj** [comment]
image

**Review by lopopolo — APPROVED** [review]
LGTM thank you

**Pull request merged**
